name: lesson

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  if-windows-els:
    runs-on: ubuntu-latest

    steps:
      - if: runner.os == 'Windows'
        run: echo "test=hello\nworld" >> $GITHUB_OUTPUT
      - if: runner.os != 'Windows'
        run: echo Os is not Windows, it is $RUNNER_OS
