name: lesson

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  myjob:
    runs-on: ubuntu-latest
    
    steps:
      - id: first
        run: echo "hello" >> $GITHUB_OUTPUT
      - name: secons
        run: echo $GITHUB_OUTPUT