name: lesson

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  myjob:
    runs-on: ubuntu-latest
    
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}


    steps:
      - id: first
        run: echo "hello" >> $GITHUB_OUTPUT
      - name: secons
        run: echo $GITHUB_OUTPUT