name: lesson

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  if-windows-else:
    runs-on: ubuntu-latest

    steps:
      - if: runner.os == 'Windows'
        run: echo OS is $RUNNER_OS 
      - if: runner.os != 'Windows'
        run: echo OS is not Windows, it is $RUNNER_OS
