name: lesson

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  myjob:
    runs-on: ubuntu-latest

    steps:
      - id: first
        run: echo "test=hello" >> $GITHUB_OUTPUT
      - name: print value
        run: echo ${{ steps.first.outputs.test }}